id = "mustache-json5"
name = "Mustache JSON5"
description = "Language support for Mustache JSON5 templates with syntax highlighting and formatting"
version = "0.1.0"
schema_version = 1
authors = ["Tree-sitter-mustache-json5 Contributors"]
repository = "https://github.com/patiwet/tree-sitter-mustache_json5"

[grammars.mustache_json5]
path = "grammars/mustache_json5"
