id = "mustache-json5"
name = "Mustache JSON5"
description = "Language support for Mustache JSON5 templates with syntax highlighting and formatting"
version = "0.1.0"
schema_version = 1
authors = ["Tree-sitter-mustache-json5 Contributors"]
repository = "https://github.com/tree-sitter/tree-sitter-mustache_json5"

[language]
name = "Mustache JSON5"
grammar = "mustache_json5"
path_suffixes = ["mustache_json5", "mjson5"]
line_comment_tokens = ["//"]
block_comment_tokens = [["/*", "*/"]]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{{{", end = "}}}", close = true, newline = false }
]

[language.formatter]
external = { command = "mustache-json5-fmt", arguments = ["--stdin"] }

[grammars.mustache_json5]
repository = "https://github.com/tree-sitter/tree-sitter-mustache_json5"
commit = "HEAD"
