name = "Mustache JSON5"
grammar = "mustache_json5"
path_suffixes = ["mustache_json5", "mjson5"]
line_comments = ["//"]
block_comment = { start = "/*", end = "*/" }
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false }
]

[formatter]
external = { command = "mustache-json5-fmt", arguments = ["--stdin"] }
